INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (1, 'Print', 2, 'Service', 'We can print with a high quality and the best prices');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (2, 'Design', 15, 'Service', 'We can design and create a new image for your product');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (3, 'Installation', 12, 'Service', 'Professional that can save you time and effort');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (4, 'Banner', 7, 'Material', 'Banner is the best material for your exteriors');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (5, 'Vinyl', 8, 'Material', 'Vinyl is the best material for your interiors');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (6, 'Shinning vinyl', 10, 'Material', 'Shinning vinyl is the best material for your interiors');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (7, 'Roll-up', 15, 'Structure', 'Roll up is the best structure for your conferences, portable and strong');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (8, 'Spider', 20, 'Structure', 'Spider is the best structure for your pocket, it is flexible and it helps your banner to stay up-');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (9, 'Vinyl Banners', 3, 'Signs & Banner', 'Advertise, announce or celebrate with vinyl banners.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (10, 'Retractable Banners', 3, 'Signs & Banner','Make the most of your event time and space.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (11, 'Mesh Banners', 3, 'Signs & Banner','Stand out to customers. Stand up to the elements.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (12, 'Postcards', 3, 'Marketing Materials','Spread the word, the tried-and-true way.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (13, 'Flyers', 3, 'Marketing Materials','Reach new customers – anytime, anywhere.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (14, 'Brochures', 3, 'Marketing Materials','Reach new customers – anytime, anywhere.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (15, 'Door Hangers', 3, 'Marketing Materials','Put your message in a spot people just can’t miss.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (16, 'Mugs', 3, 'Promotional Products','Customize with photos, text & more. 11oz capacity, microwave-safe.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (18, 'Calendars', 3, 'Promotional Products','Organize the year and turn your favorite photos into a custom calendar— with options for your home, office and more.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (19, 'Watter Bottles', 3, 'Promotional Products','A stylish bottle to showcase your brand.');
INSERT INTO printerstore.product (id, name, price, type_name, description) VALUES (20, 'Canvas Prints', 3, 'Wall art','Transform your logo into a work of art.');

